### ISSUE TITLE
optimize: error handling for Problem.Func etc.

### ISSUE THREAD

**Issue by theGreatWhiteShark** [gonum/gonum#1017]
Using current master of `gonum/optimize` 4340aa3 I struggle implementing the minimization of a rather complex objective function `Problem.Func`.

Imagine we have something like
```go
func objectiveFunction(x []float64) float64 {
  ...
  var matrixChol mat.Cholesky
  ok := matrixChol.Factorize(&matrix) 
  if !ok {
     errors.New("Error calculating the Cholesky decomposition")
  }
  ....
```

The matrix, which is about to be decomposed, depends on the input `x` and I can not guarantee that it is indeed semi-definite.

I could not find anything in the documentation, issues, etc. regarding how to "abort" the optimization and the signature of `Problem.Func`, `Problem.Grad`, and `Problem.Hess` prevent handing over an error to signalize the optimization routine that somethings is off.

As far as I understand the concept of the language (https://golang.org/doc/faq#exceptions) the best way to add this support would be to allow the afforementioned functions to return an error as well.

I would of course help to implement the feature ;)

**Comment by btracey** [comment]
- The direct answer to your question is to use the `Status` function of Problem. https://godoc.org/gonum.org/v1/gonum/optimize#Problem  Return NotTerminated until you hit this error, return a large problem when the decomposition falis, and then return an error status. 

- Alternately,  you could treat the condition like a constraint, and return `math.Inf` if the decomposition errors (or probably better use some kind of barrier function on the condition number). This would drive the optimization to solutions where the decomposition exists.

- Reparametrize x such that the decomposition has to succeed, for instance parametrize the Cholesky decomposition directly rather than the elements of the symmetric matrix.

**Comment by vladimir-ch** [comment]
@theGreatWhiteShark Do you think you could share more information about what you are trying to do and how your objective function looks like?

**Comment by theGreatWhiteShark** [comment]
Hey,

So, I'm fitting a Gaussian process to some data and do use the log-likelihood and its gradient (see https://www.jstatsoft.org/article/view/v051i01 appendix A). _Park JS, Baek J (2001). “Efficient Computation of Maximum Likelihood Estimators in a Spatial Linear Model with Power Exponential Covariogram.”_ (unfortunately not open access) provided a quite efficient version of both equations depending on a Cholesky decomposition and backsolving a number of systems of linear equations.

I do think returning `math.Inf(1)` in a minimization process is a quite elegant solution of the problem (which I also use for parameters smaller than zero to implement some box constraints right now). Actually, I also thought about returning either `math.Inf(1)` or `math.NaN()` beforehand but was not sure what would happen internally. Maybe that's something worth noting in the documentation.
