### ISSUE TITLE
dsp/window: revisit window function definitions' use of N-1 vs N

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#1240]
See https://github.com/gonum/gonum/pull/1230#pullrequestreview-360730303

**Comment by kortschak** [comment]
This turns out to be a philosophical question, that is whether we are using half open or open intervals. Normally I'd argue we're using half open, but in this instance open seems more appropriate.

**Comment by vladimir-ch** [comment]
In some sense it is philosophical but it does have practical consequences. For example, currently the sine window does:
```
	k := math.Pi / float64(len(seq)-1)
	for i := range seq {
		seq[i] *= math.Sin(k * float64(i))
	}
```
Note that the weight for the first and last sample is 0 (in floating point maybe not exactly) and so the samples are effectively discarded. It would make much more sense to exclude zero weights from the window function because the window function is already implicitly zero outside of the window. That's why "Introduction to digital audio coding and standards" has `1/2` in the formulas; they assume that the samples represent a value of the signal in the middle of (short) sampling intervals. This should be consistent across all the windowing functions and ideally there should be a package-wide convention about this, too.

**Comment by kortschak** [comment]
>This should be consistent across all the windowing functions and ideally there should be a package-wide convention about this, too.

SGTM

I'm happy to follow the convention of only zero outside the window.

**Comment by goofinator** [comment]
For example: https://en.wikipedia.org/wiki/Window_function#Sine_window gives us: w[n]=sin(π*n/N), 0≤n≤N. it's correspond to 0 value on n=0,N.
Currently we use whole diapason of values [0,N-1] , where N=len(seq). If you try to use w[n]=sin(π*n/N), in case of right point n=N-1 it gives you w[N-1]=sin(π*N-1/N), n=N-1, which is a smaller, but a gap of function.

**Comment by kortschak** [comment]
What @vladimir-ch is suggesting, is that we shift the window so that the zero end-points are omitted. In "Introduction to digital audio coding and standards", the implementation of the Sine window is given as 

> Note that when applied to discrete time signals over N samples this window is implemented as
>     w_s[n) = sin[π(n+1/2)/N) for n=O, ... ,N-1

**Comment by goofinator** [comment]
so, we have no gap, because points, that should give a zero value have been moved outside of sequence? nice.

**Comment by kortschak** [comment]
Yeah

**Comment by goofinator** [comment]
I'll take care of it, if you don't mind.

**Comment by kortschak** [comment]
I've sent it; #1242.
