### ISSUE TITLE
mat: inconsistent naming VecDense.CloneVec vs Dense.CloneFrom

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/gonum#1264]
`VecDense.CloneFromVec` seems to get too long, so rather change to `Dense.Clone` (as in `Dense.Copy`)?

**Comment by kortschak** [comment]
For reference the change of `Clone` to `CloneFrom` was made in #992 to partially address #991. Note that #991 is not closed yet since the reason for the name change was not added. The method addition that was being asked for there, `Clone() Matrix`, also had an alternative, `CloneOf() Matrix`, which I still don't think reads as well.

I think `CloneFromVec` is OK (or at least, least worst).

**Comment by vladimir-ch** [comment]
Ok, I'll submit a PR with `CloneFromVec`.
