### ISSUE TITLE
README: add TODOs Badge

### ISSUE THREAD

**Issue by patrickdevivo** [gonum/gonum#1274]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/gonum/gonum)](https://www.tickgit.com/browse?repo=github.com/gonum/gonum)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/gonum/gonum)](https://www.tickgit.com/browse?repo=github.com/gonum/gonum)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

(full disclosure, I am the creator/maintainer of `tickgit`)

**Comment by kortschak** [comment]
Thank for pointing to this. It seems like a pretty useful tool (though we are starting to look like a South American dictator with number of badges we have - maybe it should go on the Issues heading).

I had a look at the site and the executable and there's a couple of bits of feedback I hope are helpful:

1. The site would benefit I think from the ability to sort by time and group by author.
2. The layout of the src directories in the tickgit repo results in building a `cmd`-named executable rather than a `tickgit`-named executable when the obvious conventional approach to installation is used (there are no instructions to the contrary). Given that the repo has only one command I'd suggest moving the contents of augmentable-dev/tickgit/cmd to the root of your repo.

**Comment by patrickdevivo** [comment]
Hi @kortschak thanks so much for the feedback, both points are extremely helpful and make a ton of sense! I hope to implement them soon and can report back here once done.
