### ISSUE TITLE
Proposal: Change the graph.Adder interfaces to report error instead of panicking.

### ISSUE THREAD

**Issue by MatthewRock** [gonum/gonum#1279]
### Background
Gonum has a few interfaces called `Adder`. They are similar in that they all have a `AddX/SetX` method which mutates the receiver and **panics** if the action has happened in the past (e.g. adding the same node to the graph twice).

The types I have in mind are:
`WeightedLineAdder` , `EdgeAdder`, `LineAdder`, `NodeAdder`, `WeightedEdgeAdder`
and functions `Copy`, `CopyWeighted`.

Panic is not an idiomatic way to report an error in golang though. Usually, panics are reserved for grave errors that are expected to crash the program. It's not easy to use - you have to `defer recover()`, but then it's not easy to distinguish this panic from other panics. 

I am also aware of [this conversation](https://groups.google.com/forum/#!searchin/gonum-dev/panic%7Csort:date/gonum-dev/YVOBAPWpH_8/DnBz9VorAQAJ) but I believe that adding a duplicate is not a situation that requires the panic to happen.

### Proposal

Change the interface to return an error instead of panicking. Concrete example 
Before:
```golang
type NodeAdder interface {
	// NewNode returns a new Node with a unique
	// arbitrary ID.
	NewNode() Node

	// AddNode adds a node to the graph. AddNode panics if
	// the added node ID matches an existing node ID.
	AddNode(Node)
}

```

After:
```golang
type NodeAdder interface {
	// NewNode returns a new Node with a unique
	// arbitrary ID.
	NewNode() Node

	// AddNode adds a node to the graph. AddNode returns an error if
	// the added node ID matches an existing node ID.
	error AddNode(Node)
}
```

Usage 
Before:

```golang
func safeAddNode(g NodeAdder, n Node) (err error) {
    defer func() {
                if r := recover(); r != nil {
                    err = fmt.Errorf("%s", r)
                }
    }
    g.AddNode(n)
}

func main() {
    // initialize g and n...
    if err := safeAddNode(g, n); err != nil {
        log(err)
    }
}
```
After:

```golang

func main() {
    //initialize g and n...
    if err := g.AddNode(n); err != nil {
        log(err)
    }
}
```

If you wish to leave the panicking calls, it would appear that idiomatic way to do it is by prepending a "Must", e.g. `MustAddNode()` in a similar fashion to `regexp.Compile` and `regexp.MustCompile`. 

### Potential impact of proposal
Implementation is easy. 
The change would require an update from the API users to handle `error` instead of relying on `panic` and/or capturing it.

**Comment by kortschak** [comment]
Thank you for the proposal, but this will not happen. The use of panics in the places where they exist in the Gonum suite are consistent and have been something that we have put a lot of thought into. While there is the claim that the use of panics for errors is non-idiomatic in Go, the reality is more nuanced; errors are for things that you, as a package client, can not have a way of knowing ahead of the call while panics are for things that you can reasonably be aware of, or are catastrophic. Panics are also used to simulate a type system where the Go type system is inadequately strong to describe the underlying model of reality that the code is attempting to reflect. An example of this is the mat package, where the mathematics of matrices has a type system that includes dimensionality, but which Go's type system cannot handle at compile time.

In addition to this, there is a fundamental difference between the underlying motivations for Gonum and industrial Go use; Gonum is a primarily a scientific software suite, which means that results must be trustable. To prevent the (all too common) case of users forging ahead and using errored computation and generating an incorrect result, we panic, bringing down the application, rather than continuing with execution. We have identified a number of common errors and the packages we publish are written to help avoid these. This is described in slide 21 of my talk on the history of Gonum [last year](https://talks.godoc.org/github.com/gonum/talks/2019/accidental.slide#21). It's worthwhile noting that with the API you propose, it is easy for a user to ignore the returned error, since that is the only return.

Renaming panicking functions is not an option, it would be unnecessarily onerous to users and is not something that is standard practice, unless there are alternative functions that return errors. Looking at the reflect package is informative in this, and in the previously noted cases where a type system is simulated at run time.
