### ISSUE TITLE
Syntax error while trying to install gonum

### ISSUE THREAD

**Issue by nikhilnfer** [gonum/gonum#1307]
### What are you trying to do?
Install gonum on Ubuntu

### What did you do?
go get -u gonum.org/v1/gonum/...

### What did you expect to happen?
Installation of gonum 

### What actually happened?
Syntax Error 
```
# gonum.org/v1/gonum/lapack/gonum
/home/rohit/go/src/gonum.org/v1/gonum/lapack/gonum/lapack.go:39:15: syntax error: unexpected p, expecting semicolon or newline or )
```

### What version of Go and Gonum are you using?

go version go1.12.9 linux/amd64
962425fcd95aa0b51171a6a7fbf505035763fbf6

### Does this issue reproduce with the current master?
Yes

**Comment by kortschak** [comment]
Please answer all of the questions in the template. With an explicit Gonum and Go version I can be 100% certain that you are attempting to install Gonum with an unsupported Go version; we only [support the two most recent releases of Go](https://github.com/gonum/gonum#supported-go-versions). Currently this is 1.14 and 1.13.

The issue you are seeing is because we are using the binary floating point format for defining constants in `lapack.go`. This was introduced in Go 1.13.

**Comment by cj-bradley** [comment]
Also encountered the issue on 1.12, upgraded to 1.14, issue cleared
