### ISSUE TITLE
mat: linear equation solver for triangular band matrices missing

### ISSUE THREAD

**Issue by romanwerpachowski** [gonum/gonum#1471]
### What are you trying to do?

I want to solve a linear equation system described by a triangular banded matrix. This is for an implementation of an interpolation algorithm.

### What did you try?

I looked at `mat/solve.go`, but it only handles general dense matrices.

### How does Gonum not allow you to achieve your goal?

Current `mat.Solve()` is too slow for the intended purpose (fitting a spline interpolator, which can be done many times when calculating sensitivities to inputs, for example).

### What version of Go and Gonum are you using?

go version go1.14.3 windows/amd64

Gonum is current master.

### Is this feature absent from the current master?

Yes.

### Are you able to help contribute the feature?

Yes.

**Comment by kortschak** [comment]
Does #1441 add what you need?

**Comment by vladimir-ch** [comment]
Are you sure you need only a triangular band matrix solver or actually the banded LU decomposition? The former would mean adding `TriBandDense.SolveTo` and `SolveVecTo` and calling to `blas64.Tbsv` (available) or to lapack's DTBTRS (not done yet but it's just a tiny wrapper for TBSV which adds a singularity check). The latter would mean more work of porting lapack's DGBTRF et al. to Go and adding a new type to `mat` that would represent the banded LU factorization similarly to what #1441 does for banded Cholesky factorization.

**Comment by romanwerpachowski** [comment]
I just need a triangular band solver.

**Comment by vladimir-ch** [comment]
Ok. Having a banded LU factorization would still be nice.

> adding TriBandDense.SolveTo and SolveVecTo

I checked and actually the correct way would be to add a special case for triangular band matrices to `Dense.Solve` and `VecDense.SolveVec`.

**Comment by romanwerpachowski** [comment]
I agree.

**Comment by btracey** [comment]
Why?

I think in general it would be best to move away from type casting, and
more toward interfaces wherever possible. I think this is possible when
operations involve one "important" matrix (Solve, Trace), and hard when
they involve multiple (Mul).  The reason is that this makes it really easy
to interoperate with sparse matrices and the like.

The suggestion is that Solve (and things like it) follow the pattern
established in mat.Trace. Check if the matrix has an appropriate method. If
it does, use the fast version. If it does not, convert to a dense and use
the dense implementation. This keeps all "type specific" logic within the
type. We then correspondingly augment the mat types to have these methods.
For Solve, this is refactoring to make SolveTo and SolveVecTo the
"principal" methods.

**Comment by kortschak** [comment]
I agree with @btracey; the `Dense.Solve*To` should be for general matrices. In the older design we had, it would have made sense to have assertions deciding how to behave (I looking into this, I found at least one case where the documentation in mat has scars of this behaviour in a reference to `*Dense.SolveCholesky` - I'll go over the docs and check for more of these), but now it makes much more sense to work with the behaviours at the function signature level.

**Comment by vladimir-ch** [comment]
Yes, I also agree, that's why my original suggestion was to add `TriBandDense.SolveTo`. I thought that that's what we're already doing for other matrix types but got confused when I saw that we're actually not.

**Comment by romanwerpachowski** [comment]
I've just realised that I actually need a triband diagonal matrix decomposition, as @vladimir-ch said at the beginning of the thread :(

**Comment by vladimir-ch** [comment]
No worries, this was a low-hanging fruit and a useful addition anyway.

**Comment by vladimir-ch** [comment]
By the way, Lapack has a dedicated tridiagonal solver (DGTTRF et al). This would be more work not only in our `lapack` but also in `mat` because we would need a tridiagonal matrix type and factorization type. It could be more efficient than a banded LU factorization but banded LU is of course more general. I'll check the Lapack code and create an issue for the tridiag solver.
