### ISSUE TITLE
gonum/simple: Undirected.Edge(),EdgeBetween() return inconsistent underlying type

### ISSUE THREAD

**Issue by jfcantu** [gonum/gonum#1502]
In the `simple` package, `Undirected.Edge()` and the underlying `Undirected.EdgeBetween()` return a `graph.Edge` interface.

However, if the `from` and `to` parameters are passed in reverse order, the underlying type will always be a `simple.Edge` - which will cause a panic if the caller is expecting a different implementation of `graph.Edge`.

### What are you trying to do?
Build an UndirectedGraph with the ability to attach data to an Edge.

### What did you do?
See https://play.golang.org/p/CNftRDSnF7X - note that it doesn't run successfully in Go Playground because importing the module causes it to time out.

### What did you expect to happen?
I expected `UndirectedGraph.Edge()` to return the same type that I passed to `UndirectedGraph.SetEdge()` when adding the Edge to the graph.

### What actually happened?
If the first parameter to `Edge()` matches the node that gonum considers the "From" node, then it will return the Edge as it was passed to `SetEdge()`, which is the correct type. However, if the first parameter matches the "To" node, then gonum will call `ReversedEdge()` on the edge and return the result - which is always a `simple.Edge`.

### What version of Go and Gonum are you using?
`go version go1.14.4 windows/amd64`

```
gonum.org/v1/gonum v0.0.0-20180816165407-929014505bf4/go.mod h1:Y+Yx5eoAFn32cQvJDxZx5Dpnq+c3wtXuadVZAcxbbBo=
gonum.org/v1/gonum v0.8.1 h1:wGtP3yGpc5mCLOLeTeBdjeui9oZSz5De0eOjMLC/QuQ=
gonum.org/v1/gonum v0.8.1/go.mod h1:oe/vMfY3deqTw+1EZJhuvEW2iwGF1bW9wwu7XCu0+v0=
```

**Comment by kortschak** [comment]
Thanks for the report.

The problem you are seeing is because you are embedding `simple.Edge` in `customEdge`. This would make sense if Go had inheritance, but it doesn't; what happens is that the embedded type's method is called without any knowledge of the embedding type.

The correct approach is to implement the three methods on your `customEdge` as I've done [here](https://play.golang.org/p/ROS3mY10vCg). Note that I've removed the pointer from the `customEdge` because in this example it is not necessary (it may be in your case) and it simplifies the code for `ReversedEdge` (which would otherwise need to copy the struct to prevent mutating the copy held by the graph).

**Comment by kortschak** [comment]
If you still believe this is an issue, please re-open.
