### ISSUE TITLE
mat: make Vector an interface type and rename the concrete type

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#151]
There is a need for the vector type to be an interface if we want to be able to interoperate GPU computation with the CPU implementation we have in an efficient way. To address this the current `Vector` type needs to be renamed.

Options?

1. `ColumnVector`
2. `ColVector`
3. `VectorCol`
4. `Column`
5. other (`VectorDense` does not seem appropriate since it isn't necessarily dense)?

Thoughts?

**Comment by btracey** [comment]
I think `VecDense` fits best. It fits with the other naming schemes, and it's not necessarily dense, for instance, if it's sparse.

**Comment by kortschak** [comment]
`VecCol`?

I don't understand the argument here for dense "It fits with the other naming schemes, *and it's not necessarily dense*, for instance, if it's sparse".

**Comment by btracey** [comment]
The problem with VecCol is that it's not different from Vector. The Vector interface represents a column vector. I don't think there's a reason to have an additional VecRow since we have the `T` method

By fits in with the naming scheme, we have
Matrix -> Dense
Symmetric -> SymDense
Triangular -> TriDense
Banded -> BandDense

It seems reasonable for the pattern to continue with
Vector -> VecDense

Our current implementation is not the only reasonable thing to implement the interface, for instance someone could implement a VecSparse that implements the Vector interface

```
type VecSparse struct {
     data map[int]float64
}

func (v VecSparse) At(i,j int) {
     return v.data[i]
}
```

**Comment by kortschak** [comment]
Fair enough. `VecDense` it is.

**Comment by btracey** [comment]
This is fixed, right?

**Comment by kortschak** [comment]
I wasn't thinking so since the signatures and bodies need to be updated in functions taking `*VecDense`, but that can be another issue.

**Comment by kortschak** [comment]
That is now #167.

**Comment by kortschak** [comment]
>The Vector interface represents a column vector.

This is a little complicated. The transpose of a Vector satisfies a vector (if we want to use `.TVec()` in places like `SolveVec` as we do with `Dense` in other places). It becomes convention that an untransposed vector is a column and a transposed vector is a row. So we need to document this. I'm sending a prelude to addressing some of #167 in a few minutes. The first commit is necessary, but the second commit explores this.
