### ISSUE TITLE
gonum/spatial/r3: Add Euler/Tait-Bryan angle rotations

### ISSUE THREAD

**Issue by soypat** [gonum/gonum#1678]
### Background
Analysis of rigid body mechanics in 3D space are usually dealt with in Euler angles in introductory literature to simplify the algebra. Such is the case in _Rigid Body Dynamics_ by Prof. Hubert Hahn whose book deals with the XYZ permutation of Tait-Bryan angles. 

### Proposal
Add an implementation of the XYZ Tait-Bryan rotation.

### Potential impact of proposal
It is known this representation has the problem of gimbal lock. Maybe users could have the option to convert the Tait-Bryan rotation into a quaternion rotation to avoid this problem.

**Comment by kortschak** [comment]
A similar proposal has been made in the past https://github.com/gonum/gonum/issues/1552 that suffers from the same problems which I wrote about [here](https://github.com/gonum/gonum/pull/1516#discussion_r532911007).

This proposal says that the algebra is easier. Can this be demonstrated? I would have thought the converse since the rotation operation with a quat is simple and operations on quats are simple, including Slerp.

If the addition of this feature for learning purposes (being able to understand the literature), then I would much rather have an example test that shows interconversion between angle-based forms and quats and which demonstrates the outcome of attempting this with a gimbal locked system (note here that converting a description of a rotation system with gimbal lock into a quat representation doesn't solve the gimbal lock).

**Comment by kortschak** [comment]
A fleshed out (more detail on gimbal lock) version of this would be pretty reasonable.

```
package r3_test

import (
	"fmt"
	"math"

	"gonum.org/v1/gonum/spatial/r3"
)

// euler returns an r3.Rotation that corresponds to the Euler
// angles alpha, beta and gamma which are rotations around the x,
// y and z axes respectively.
func euler(alpha, beta, gamma float64) r3.Rotation {
	s1, c1 := math.Sincos(alpha / 2)
	s2, c2 := math.Sincos(beta / 2)
	s3, c3 := math.Sincos(gamma / 2)
	return r3.Rotation{
		Real: c2*c1*c3 - s2*s1*s3,
		Imag: s2*s1*c3 + c2*c1*s3,
		Jmag: s2*c1*c3 + c2*s1*s3,
		Kmag: c2*s1*c3 - s2*c1*s3,
	}
}

func ExampleRotation_gimbalLock() {
	orig := r3.Vec{-1, 0, 0}

	fmt.Printf("rotate around y-axis: %.0f\n", euler(0, math.Pi/2, 0).Rotate(orig))
	fmt.Printf("rotate around z-axis: %.0f\n", euler(0, 0, math.Pi/2).Rotate(orig))
	fmt.Printf("gimbal lock: %.0f\n", euler(0, math.Pi/2, math.Pi/4).Rotate(orig))

	// Output:
	//
	// rotate around y-axis: {-0 0 1}
	// rotate around z-axis: {-1 0 0}
	// gimbal lock: {-0 0 1}
}
```

**Comment by soypat** [comment]
> `fmt.Printf("rotate around z-axis: %.0f\n", euler(0, 0, math.Pi/2).Rotate(pt))`
> Output: `rotate around z-axis: {-1 0 0}`
huh? Rotating (-1,0,0) around z axis should change the vector. Result should be (0 1 0)

Alright, I think I understand. So it would be enough to add examples on how to implement euler angles in the docs. Should I draft up examples and descriptions of applications and limitations?

**Comment by kortschak** [comment]
Yeah, bugs were found. I have a more fleshed out version here. I want to spend some time on the commentary though. I'll send it soon.
