### ISSUE TITLE
Use generics for the Graph library

### ISSUE THREAD

**Issue by globalflea** [gonum/gonum#1854]
Currently, the graph ids are hard coded as int64.  It would be better if it was a generic type, maybe `constraints.Ordered` or `comparable`.  This would allow ids of different types - e.g. int (different sizes of), string

Additionally, it may be better to separate ID management (Use or Release) separately from the Graph lib

**Comment by kortschak** [comment]
It's unclear to me why this would be a benefit; the node ID is an anonymous identifier and it not an information carrier beyond that. Users of graphs are able to embed or otherwise map nodes/IDs to other values associated with their application-specific graph problems. See https://www.gonum.org/post/word_ladder/ for an example of this. Making node IDs more generic would complicate the code and even if it were a good idea would take an enormous effort.

**Comment by globalflea** [comment]
thanks

**Comment by lllamnyp** [comment]
> It's unclear to me why this would be a benefit

Here's a use-case I have. I'd like to visualize my AWS infra with VPCs as nodes and peering connections between them as edges. It would be natural to use the VPC IDs as node IDs, but since VPC IDs are of the form `vpc-<some hex string>`, I have to maintain a mapping between the `int64` IDs of nodes and the IDs of VPCs.

**Comment by kortschak** [comment]
> I have to maintain a mapping between the `int64` IDs of nodes and the IDs of VPCs.

You would need to do that anyway since many aspects of the graph code depend on numeric IDs. If the hex string is something that fits into 64 bits, then the mapping is trivial and we already would cope with it without using type parameters.

**Comment by miparnisari** [comment]
If I may chime in, I'm evaluating this library versus https://github.com/dominikbraun/graph. The only downside I can find in gonum is... readability.

Consider this code from the other library:


```go
g := graph.New(graph.StringHash, graph.Directed())
g.AddVertex("london")
g.AddVertex("paris")
_ = g.AddEdge("london", "paris")
```

This in gonum would look like:

```go
type cityGraph struct {
	ids map[string]int64
	*simple.UndirectedGraph
}

type node struct {
	city string
	id   int64
}

func (n node) ID() int64      { return n.id }
func (n node) String() string { return n.city}

u := g.UndirectedGraph.NewNode()
uid := u.ID()
u = node{city: "london", id: uid}
g.UndirectedGraph.AddNode(u)

v := g.UndirectedGraph.NewNode()
uid = v.ID()
v = node{city: "paris", id: uid}
g.UndirectedGraph.AddNode(v)

from := g.UndirectedGraph.Node(g.ids["london"])
to := g.UndirectedGraph.Node(g.ids["paris"])
g.SetEdge(simple.Edge{F: from, T: to})
```

Which one is less frightening to look at?

**Comment by kortschak** [comment]
Fear is subjective. I'm afraid of the unknown, so the first is more scary to me.

**Comment by miparnisari** [comment]
> Fear is subjective. I'm afraid of the unknown, so the first is more scary to me.

🙄 Okay. Which one would be less frightening to look at _from the perspective of someone who's never used either library before _?

**Comment by kortschak** [comment]
Depends on what they are trying to do; I should have been more clear, not that I don't know that other library, but it is not being explicit which is a design goal of the Gonum packages. However, the design of the Gonum graph packages' API is not going to change at this point, so this is moot.
