### ISSUE TITLE
mat/prodcut.go invalid link in the comment

### ISSUE THREAD

**Issue by ksw2000** [gonum/gonum#1966]
I found an invalid link in the comment within the Product() function when attempting to implement the more efficient algorithm.

https://github.com/gonum/gonum/blob/219257751c13c784917a3e62f5023a04675d6535/mat/product.go#L21

![image](https://github.com/gonum/gonum/assets/13825170/76387855-20e9-4580-910f-7ac1be51b12c)

**Comment by kortschak** [comment]
I may have that paper somewhere. I'll look on the weekend.

**Comment by kortschak** [comment]
I was unable to find the paper (the work station I was working on when this was written has long since been retired). However, I have found this: https://en.wikipedia.org/wiki/Talk%3AMatrix_chain_multiplication, which does refer to the article and (due to JofCIS not being available), quotes the algorithm. If you have access to IEEE or know someone who does, then that would probably be the best path forward, or if you know someone at a university with access to JofCIS.

For future reference, the title of the paper, which I should have included, is "An Efficient Algorithm for Chain Multiplication of Dense Matrices and Its Computer Implementation", Journal of Computational Information Systems 10: 10 (2014) 4299–4306, Daxin ZHU, Yingjie WU, and Xiaodong WANG.
