### ISSUE TITLE
mat: get diagonal of a matrix

### ISSUE THREAD

**Issue by buyology** [gonum/gonum#213]
as per discussion with @btracey on slack, it'd very handy to be able to extract the diagonal of a matrix for e. g. extracting the variance from a varcov matrix (cf. `numpy.diag` when operating on a matrix)

possibly as a view directly on the matrix:

```go
func (m *Dense) DiagView() SymBandDense {}
```

or

```
func (m *Dense) DiagView() Dense {}
```

or

```go
func (s *SymBandDense) GetDiag(a Matrix)
```

**Comment by btracey** [comment]
The first should be `SymBanded`, the interface, not the concrete type.

The second signature can't happen, because you can't return a `*Dense` that's a view of a different `*Dense` but contains different data.

**Comment by kortschak** [comment]
From a perspective of composability, it seems to me that that destination should be a `*VecDense` (`(func (v *VecDense) DiagonalOf(m Matrix)`)and the method should be on that type. There can can be a `Diagonalise(v *VecDense)` on `*SymBandDense` for cases where an actual diagonal matrix is needed.

In the cases where the input matrix is a `Raw*` type, this allows the operations of getting the diagonal vector and the diagonal matrix to not require any additional allocations.

**Comment by btracey** [comment]
I agree with Dan.

**Comment by kczimm** [comment]
Has this been implemented yet? I've began implementing the above mentioned functionality including updating vector_test.go to provide coverage. At the risk of exposing my naiveté, when I execute the command `go test -run TestVecDenseDiagonalOf`, the following error message is printed:

`inner.go:9:2: use of internal package not allowed`

So, two things, can anyone tell me what I'm doing wrong running the newly implemented tests? and does anyone still care enough about this functionality for me to create a PR?

**Comment by kortschak** [comment]
>when I execute the command `go test -run TestVecDenseDiagonalOf`, the following error message is printed:

>`inner.go:9:2: use of internal package not allowed`

>So, two things, can anyone tell me what I'm doing wrong running the newly implemented tests?

The issue here is likely that you have cloned a github fork of gonum/gonum into a location that is not `$GOPATH/src/gonum.org/v1/gonum`. This will not work, since it will import the code at the locations specified in the import statements. You should use an approach that is equivalent to [this](http://blog.campoy.cat/2014/03/github-and-go-forking-pull-requests-and.html).

I'm working on a PR now.

**Comment by kortschak** [comment]
This introduces/highlights some interesting API subtleties that I'm not comfortable with when implemented the most efficient way; it makes sense to allow a `DiagonalViewOf` that makes a `*VecDense` point to the diagonal of a `RawMatrixer`. A separate vector value can then be created by using `CloneVec`, but it also makes sense to allows the `Diagonalize` to take any `*VecDense`, making an allocation-free diagonal reflection of a `*Dense` possible in principle. This is nice, but problematic, since it expands the API capacity we provide beyond what our shadow detection promises. The are two obvious approaches to dealing with this:

1. Expand shadow detection to allow comparison between all `Raw*` types (this is not something I really want to do).
2. Prevent reflecting a `*Dense`'s diagonal into a `*SymBandDense` - there are two ways to do this: 1) not reflect the original `*Dense` into the `*VecDense` which seems like a shame or 2) mark the `*VecDense` as having come from a `*Dense` (in practice keeping an `int` field with a type-marking value) - this should be doable reasonably cheaply.

@btracey thoughts?

**Comment by kortschak** [comment]
Alternatively we can do rectangle shadow checks for banded matrices along as we do with `*Dense` matrices - we have not actually implemented any banded arithmetic yet, so we are free to choose.

**Comment by kortschak** [comment]
Final alternative: change shadow detection for all types to be the minimal rectangle containing the data. This means there is only a single type of comparison and all types can be checked. We lose cleverness (for example to the ability to hide two triangles in a dense), but that may not be a bad thing.

**Comment by danaugrs** [comment]
I'm looking for this functionality (i.e. obtain the diagonal of a matrix) is there any plan in place to implement it?

**Comment by kortschak** [comment]
I'm working on striding the `DiagDense` type right now. The capacity to extract a diagonal may go in the same PR.
