### ISSUE TITLE
all: reduce dependency of randomised tests on random stream implementation details

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#288]
The change in golang/go@caae0917bff12751019cb4240e99874fa692e770 to rand.Perm breaks `TestImportance` in samplemv and `TestMetropolisHastings` in sampleuv.

Example [here](https://travis-ci.org/gonum/gonum/jobs/292985969#L2272-L2291).

We should probably try to figure out a test that is less sensitive to stream specifics (the change to exp/rand.Source will likely have impacts too #228).

/cc @josharian

**Comment by kortschak** [comment]
This is fixed by golang/go@d9a198c7d0526f00a42f00d90cc4b91802a3354c, though the sensitivity to stream specifics is still an issue.

**Comment by btracey** [comment]
Since this issue was filed, we now fix the random stream in a bunch of places. Is that sufficient? If it isn't I'm not sure what the solution is except "make the tests less flaky". Random tests will always have a small probability of failure if you can change the stream arbitrarily, but I think they serve an important use case.

**Comment by kortschak** [comment]
There's a principle in place that random streams are essentially covered by the Go1 promise, so I think we can close this.
