### ISSUE TITLE
stat: Change parity convention in ROC

### ISSUE THREAD

**Issue by MaxHalford** [gonum/gonum#316]
I was going through the ROC AUC examples and found that the results were not very intuitive. Indeed [the basic example](https://github.com/gonum/gonum/blob/master/stat/roc_example_test.go#L41) gives a ROC AUC of 0.75 but if I run it with sklearn I get:

```python
>>> from sklearn import metrics
>>> y = [0.1, 0.35, 0.4, 0.8]
>>> classes = [1, 0, 1, 0]
>>> metrics.roc_auc_score(classes, y)
0.25
```

Moreover, according to gonum a perfect match between two slices results in a ROC AUC of 0, whereas intuitively it should be 1. Initially I made [a pull request](https://github.com/gonum/gonum/pull/315) because I thought it was a typo in the examples but it turns out the problem is a bit more complicated.

**Comment by btracey** [comment]
It's not that a perfect match gives an AUC of 0, it's that our definition of a perfect match is opposite of what I would intuitively think is a perfect match. ROC treats values below the cutoff as `true` (rather than `false`), and so effectively this means that the `y` values are  "probability of being `false`", instead of the more intuitive "probability of being `true`".  I would vote we switch the function to match sklearn.

**Comment by sbinet** [comment]
fine by me.

**Comment by MaxHalford** [comment]
Are we waiting on a pull request from someone?

**Comment by btracey** [comment]
Sounds like it. Would you like to do so?

**Comment by MaxHalford** [comment]
Sure I'm on it.
