### ISSUE TITLE
stat: calculating mean over given axis

### ISSUE THREAD

**Issue by ibadami** [gonum/gonum#321]
Hi there,

Thanks a lot for this amazing numeric library in golang. 
I have recently migrated to golang from python and numpy. I apologise in advance if I am thinking too much in pythonic way while asking this question.
Is it possible to calculate mean, variance or in general any operation in the matrix over a given axis?
The example on gonum.org explains these functions over a single dimensional slice. 
For nested slice when one wants to access a column, it is only possible by a for loop over the rows and then indexing the particular column of that row. 
Do you think it is better to have these functions defined over gonum/mat as well just like numpy? 

Thank you

**Comment by kortschak** [comment]
The answer to this question depends on a number of things. If your data are in a `*mat.Dense` and you want to take means and variances etc for each row, then the easiest way is to iterate over the rows and use the `.RawRowView` method to get a `[]float64` and then you functions from the gonum/stat package.

```
r, _ := m.Dims()
for i := 0; i < r; i++ {
    fmt.Println(i, stat.Mean(m.RawRowView(i)),  stat.Variance(m.RawRowView(i)))
}
```

This cannot be done for columns because of the matrix layout, but you can do something similar.

```
_, c := m.Dims()
var col, tmp mat.VecDense
for j := 0; j < c; j++ {
    tmp.ColViewOf(m, j)
    col.Clone(&tmp)
    fmt.Println(j, stat.Mean(col.RawVector().Data),  stat.Variance(col.RawVector().Data))
}
```

This will be slower than the first because there is a copy. It work because `col` will have an increment of 1, so the data slice will mesh with the stat packages view of the world. I don't think we yet guarantee that this will always work, but the implication is there. If this breaks, I think it would be a bug and we would have to fix that.

**Comment by btracey** [comment]
One should avoid `RawVector` whenever possible. In this case

```
_, c := m.Dims()
col := make([]float64, c)
for j := 0; j < c; j++ {
    mat.Col(c, j, m)
    mean := stat.Mean(col,nil)
    var := stat.Variance(col,nil)
    fmt.Println(j, mean, var)
}
```

**Comment by kortschak** [comment]
Yes, that's nicer for the columns.

**Comment by ibadami** [comment]
@kortschak @btracey , Thanks a lot for your quick replies. I can use this easily. 
I have one more question. Do you guys see this small code snippet being included as a function for accessing rows or columns in general. This can allow users to stay in the gonum/mat ecosystem (just like numpy arrays) instead of going back and forth from mat to slice. Moreover it also facilitates calling stat functions in less number of lines. 
I have read in the introduction of gonum: "We fully recognize that sexy one-liners are rare with Gonum."  Perhaps small modification such as this can bring the ease of numpy in go while keeping all the other advantages of the language? Unless you are following a different philosophy and do not mind writing extra number of lines every time for the sake of clarity.

Note: My company is planning to use gonum extensively in future as we are migrating to golang from JS/python/c++ right now. I will be highly interested to contribute to this library if you plan to convert some functions into (almost) one liners.

**Comment by btracey** [comment]
>  Do you guys see this small code snippet being included as a function for accessing rows or columns in general. This can allow users to stay in the gonum/mat ecosystem (just like numpy arrays) instead of going back and forth from mat to slice.

I'm not sure I understand the question. `mat.Row` and `mat.Col` are small code snippets that help access rows and columns in general. There is also `Dense.RawRowView` that helps go between a matrix and a slice. I'm guessing you mean something different though.

Right now, almost all of gonum uses `[]float64` as the base operating type. `mat` is a primary exception. It is possible that we could change the whole suite to use `mat.Vector` as the base type, which would allow `Dense.ColView` to be called instead of `mat.Col`. There are a lot of benefits, however, to maintaining the base type as `[]float64`, namely simplicity and optimization opportunities from the compiler. So, I would vote against this re-writing, but it could be discussed.

What won't happen is changing all of the code to take in a `mat.Matrix`. For instance, we are not going to change to have a bunch of signatures like
```
// Mean computes the weighted mean of the matrix as specified by orientation. If orientation = 0,
// then the weighted row-wise means are returned, if orientation = 1, the column-wise means are 
// returned, and if orientation == -1 a single mean for the whole matrix is returned.
stat.Mean(m, w mat.Matrix, orientation int) []float64
```
That function is much less clear than the existing signature. It's also not clear how you'd generalize the notion. Should `optimize.Local` take in a matrix as its initial condition? What should the behavior be?

**Comment by ibadami** [comment]
@btracey Before I reply to the post above, I checked the code snippet for calculating means for columns.
`_, c := m.Dims()
col := make([]float64, c)
for j := 0; j < c; j++ {
    mat.Col(c, j, m)
    mean := stat.Mean(col, nil)
    var := stat.Variance(col, nil)
    fmt.Println(j, mean, var)
}`
I think the RawVector is unavoidable here as @kortschak suggested. Considering my data is in *mat.Dense, mat.Col function is not available for mat.Dense type. It is only available for mat.Matrix type. 
Please let me know if I am making a silly mistake here.

**Comment by ibadami** [comment]
@sbinet I was also thinking in the same line. Instead of substituting the []float64 with mat.vector, additional package can be provided. It will give lot of flexibility to the user while working with mat package.

**Comment by kortschak** [comment]
>Considering my data is in *mat.Dense, mat.Col function is not available for mat.Dense type. It is only available for mat.Matrix type.
Please let me know if I am making a silly mistake here.

The code posted will work with a single correction; `mat.Col(col, j, m)`; `*man.Dense` satisfies `mat.Matrix`, and you can see in the code that `mat.Col` will take advantage of knowing that a matrix is a `mat.RawMatrixer` (which a `*mat.Dense` is).

>Oh I am sorry for being unclear. I didn't mean the access of the rows or columns of the matrix. I meant the second point you mentioned:
stat.Mean(m, w mat.Matrix, orientation int) []float64
more like this:
stat.Mean(m, w mat.Matrix, axis int) mat.Vector
So that nDimensional matrix can be used in general with axis: [-1,n)
This would imitate the numpy mean function a great deal (again sorry for comparing the two languages, I have been working with numpy for a really long time).

This is an unlikely addition.

**Comment by btracey** [comment]
> This is an unlikely addition.

In particular 
1) If we do this, there's no good boundaries. We aren't going to re-implement all of `stat` (for instance) to allow this. Go is about composition, and this is a great case where two concepts compose.
2) If you need this a lot, it's easy to implement your own function. I personally have a couple of convenience wrappers (like your example) for things that are useful and common, but don't fit into Gonum.

**Comment by ibadami** [comment]
I understand. Thank you for your help and time :). I am closing the issue here.

**Comment by wpoquioma** [comment]
I'd just like to point out that for getting the mean of each column using @btracey solution you would need to change c for col in the line where mat.Col is used. Also the size of col in initialization should be that of the number of rows. So it would be something like this:

r, c := m.Dims()
col := make([]float64, r)
for j := 0; j < c; j++ {
     mat.Col(col, j, m)
     mean := stat.Mean(col, nil)
     var := stat.Variance(col, nil)
     fmt.Println(j, mean, var)
}
