### ISSUE TITLE
Why does "qr.Factorize" need "m > n"?

### ISSUE THREAD

**Issue by xiajohnnyxia** [gonum/gonum#362]
I am trying some py code to change in Go.When i was used the matrix's "qr factoring" by `master/mat/qr.go`.
Its code hint me that "The matrix's m must be bigger than its n."
Why doesn't the python's `np.linalg.qr` need to use?Does "m<n" is "lq"?

**Comment by kortschak** [comment]
From reading the documentation around DGEQRF there is seems no reason in principle why we need to have this restriction, though I suspect we would need to change the factor extraction routines a little.

/cc @btracey

**Comment by xiajohnnyxia** [comment]
Ok,I got it.

**Comment by xiajohnnyxia** [comment]
@kortschak How can i get the definding dis q and r?

**Comment by btracey** [comment]
Sorry, I'll look into this when I get a chance. I know I had a reason when I implemented the method, I don't remember if it is a good reason.

https://godoc.org/gonum.org/v1/gonum/mat#QR.QTo

**Comment by vladimir-ch** [comment]
See also #39 for a short previous discussion. Note that I closed #39 with a wrong reason: our `QR.RTo` and `LQ.LTo` return a `*Dense`, not a `*TriDense` as I thought.

I checked and with a few adjustments `QR` and `LQ` can be (and probably should be) modified to take any matrix shape.

**Comment by vladimir-ch** [comment]
Two reasons for enforcing that the matrix A has `m >= n` could be that if A has full column rank, the corresponding least-squares problem has a unique solution, and that the computation of the condition number of A is easily `Cond(A) = Cond(R)`. If R is upper trapezoidal, it's unclear to me how the condition number would be estimated.

So I'm still split on this. Even though we can compute the case `m < n`, it is not that useful and it is unclear how to estimate the condition number. On the other hand, panicking in that case can be obviously confusing. @btracey ?

**Comment by xiajohnnyxia** [comment]
I have find another way to work out this problem.We can fill the zero to the matrix until its n =m .And then it can caculate.

**Comment by kortschak** [comment]
I think this should be left open until a clear decision is made.

**Comment by vladimir-ch** [comment]
All theorems about the existence and uniqueness of the QR decomposition I
have seen assume m >= n and full column rank. This does not hold when m < n
or when you pad with zeros. You will get something but it might not be
unique. If you tell us more about the problem that you are solving, we may
be able to suggest a (better) solution. Are you solving an underdetermined
system?

On Jan 12, 2018 11:59 PM, "Dan Kortschak" <notifications@github.com> wrote:

Reopened #362 <https://github.com/gonum/gonum/issues/362>.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/gonum/gonum/issues/362#event-1422673170>, or mute the
thread

**Comment by kortschak** [comment]
Are we happy to close this?

**Comment by kortschak** [comment]
Removing the stability tag since changing the behaviour to relax it or adding documentation to explain it would not break existing code.

**Comment by vladimir-ch** [comment]
Yes, I think we can close this.

**Comment by kortschak** [comment]
Done
