### ISSUE TITLE
blas/gonum: check if drotmg needs this fix

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#415]
Some debugging happened on Drotmg in the OpenBLAS implementation. We should see if our implementation has the same issues 
https://github.com/xianyi/OpenBLAS/issues/1452

**Comment by kortschak** [comment]
Our code matched OpenBLAS (as of at least 00c42dc8155cabc0b28443bd647d2c268fd98bab - my last checkout of OpenBLAS), but now does not since OpenBLAS has fixed that issue (OpenBLAS now agrees with cublas).

BTW The layout of the test struct for `Drotmg` is a little confusing since Params appears at the top where I'd expect the inputs to go, rather than at the bottom with the outputs.

**Comment by kortschak** [comment]
It's not clear to me how to apply the change OpenBLAS has made [there](https://github.com/xianyi/OpenBLAS/pull/1454)

**Comment by kortschak** [comment]
I've had several goes at this, eventually just mimicking exactly the OpenBLAS C implementation and I've not been able to get tests to pass - I finally wondered if the OpenBLAS implementation passes and it doesn't. So, what is the provenance of the expected values for the tests?

**Comment by kortschak** [comment]
OK. I've looked into this more and there is definitely a problem with our code - I have reproduced the NETLIB Fortran tests and run them against our implementation and the OpenBLAS implementation. They are both wrong; ours hangs with the input (4, -1, 2, 4) (from reading the code it looks very much to me that `d2` can be zero, though that is not the cause here), and the OpenBLAS output (via the netlib package) disagrees with the Fortran truth table.
