### ISSUE TITLE
graph: Copy() of simple.UndirectedGraph to simple.DirectedGraph does not match documentation

### ISSUE THREAD

**Issue by DryHumour** [gonum/gonum#417]
### What are you trying to do?
Apply `graph.Copy()` with an `simple.UndirectedGraph` source and a `simple.DirectedGraph` destination.

(I imagine that this also affects `graph.CopyWeighted()` for the same reason outlined below.)

### What did you do?

https://gist.github.com/DryHumour/e735ebcfea35b0a73eed36eb357369b8

### What did you expect to happen?
The documentation for `graph.Copy()` says, in part,

> If the source is undirected and the destination is directed both directions will be present in the destination after the copy is complete.

### What actually happened?
Only a single direction is present in the destination.

This seems to happen because the call by `graph.Copy()` to `src.Edge()` (in this case `simple.UndirectedGraph.Edge()`) will return exactly the same edge for both `Edge(u, v)` and `Edge(v, u)` (_i.e._ the endpoints in the result are always in the order supplied when the edge was originally created, regardless of the order in the arguments when retrieving it).  This results in `dst.SetEdge()` (in this case `simple.DirectedGraph.SetEdge()`) effectively overwriting the edge it set on the first call with the (apparently identical) edge on the second call.

I hesitate to suggest a PR since it is not clear to me where the responsibility for ordering the endpoints ought to lie.  Also, as always, any change to existing behaviour runs the risk of breaking existing applications relying on the current implementation.

I would guess that `graph.Copy()` should be using something more like `dst.SetEdge(dst.NewEdge(u, v))`, which would decouple the source graph's notion of edges from that of the destination graph's.  (Similarly for `graph.CopyWeighted()`.)  However, there may well be some good reason why this is not already so.

But it could also possibly be argued that `simple.UndirectedGraph` violates the contract for `Graph.Edge()` which says "... returns the edge from u to v ..." and so implies that `Edge(u, v).From()` should always return `u` and never `v`, which is not currently the case.

Or maybe both?  Neither?  Bueller?

### What version of Go and Gonum are you using?

`go version go1.9.2 linux/amd64`
996b88e8f8941c9defdbb338bea5e239a230e742

### Does this issue reproduce with the current master?
Yes

**Comment by kortschak** [comment]
Thank you for the report. Yes, you are absolutely correct with the issue, though the undirected used of `graph.Edge` [is documented](https://godoc.org/gonum.org/v1/gonum/graph#Edge) ([it's complicated](gonum/graph##87)). I'm not happy with with how the edge API works at this stage, and of all the outstanding issues, it's the one that I feel needs the fix the most and yet is the hardest to fix in a sensible way.

OK, back to the issue at hand. It is reasonably straightforward to fix the issue with the `Copy*` functions since the addition of the `NewEdge` method to `graph.EdgeAdder`. I will send a PR later today. The PR will break using `Copy*` to copy multigraphs, but I think that is OK; new multigraph-aware copy functions can be added at a later stage if needed.

**Comment by DryHumour** [comment]
Thanks very much for confirming the design/expected/correct behaviour!

And my apologies again for not supplying a proper full PR.  I would have been blissfully ignorant of the impact on multigraphs in any case, so it's probably for the best.

On a loosely related note, I wonder if the various kinds of copy could be compounded into a single function which used type assertions (_i.e._ similar to how `DijkstraAllPaths` _et al._ deals with weighted edges)?  That may be contrary to your design goals, however.
