### ISSUE TITLE
travis: implement a generalised import blacklist checker

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#467]
See #466.

**Comment by sbinet** [comment]
That could be fun to implement.
Let me see if I can come up with something by tomorrow?

**Comment by kortschak** [comment]
There is an obvious approach that is unfortunately incorrect; there are generated files that get modified by goimports (which is probably what we want to check against). So files containing the codegen warning should be skipped.

**Comment by sbinet** [comment]
why?
I mean, IIUC, `goimports` introduced `github.com/gonum/floats` on your setup because it's a shorter path than `gonum.org/v1/gonum/floats` (and shorter paths win when there are duplicates) and because you still have either the `floats.a` binary installed or the sources of that old package somewhere in your `$GOPATH`(s).

the way I see it, it's a problem on your end, like forgetting to run `gofmt` before submitting some human written code as a PR :)

**Comment by kortschak** [comment]
I'm not sure I understand the "why?"

Generated code does not have to follow the same rules as other code. The generated code we produce does follow `gofmt`, but it does not follow `goimports` import block structure rules. That's the problem.

**Comment by sbinet** [comment]
I thought this issue was about checking that we didn't import, say, `"github.com/gonum/floats"` by mistake (either from autocompletion, (old) muscle memory, or some other way).
I don't see how this has anything to do with `goimports` not following Gonum's preferred block structure.

**Comment by kortschak** [comment]
It's been a long day. I had two thoughts in my mind and erroneously thought people would practice telepathy and fix the conflation.

When I was following up the incorrect import, I noticed that doing to goimports check in .travis/check-formatting.sh is not used, and looked to see why. The idea of a generalised import checker and generalised goimports fmt checker merged in my mind and only one thought came out. This is still useful, but we need the other as well. It could be done in the same code you are working on.

Apologies for the confusion.
