### ISSUE TITLE
graph/encoding/dot: NewEdge method of Builder is troubling

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#56]
@mewmew I'm troubled by the presence of the NewEdge method in the Builder interface. I can see why it's there, but it is almost the same as SetEdge, and that's a problem. Possibly it could go away in the changes associated with the fix to #31?

**Comment by mewmew** [comment]
I'm definitely open to getting rid of NewEdge and agree that it is too similar to SetEdge. The main difference is that NewEdge doesn't update edges if there already exists an edge between `from` and `to`, but simply returns it instead.

In general I think there is quite a bit of cleanup we can do in the encoding/dot package, both API and internals, and I'm very glad to see that you've started to take a stab at it : )

**Comment by mewmew** [comment]
I wrote another user-defined graph today which implemented the method sets required for encoding/decoding. Doing so made me recall additional rationale why `NewEdge` was added in the first place. For the very same reason that `NewNode` was added (to be used instead of `NewNodeID` and `AddNode`).

The graph decoding library cannot know about user-defined node and edge types, but somehow has to be able to create them. Thus `NewNodeID` in combination with `AddNode` is not enough, so `NewNode` was added. The same logic applies to `NewEdge`.

**Comment by kortschak** [comment]
Yeah, that's fair enough. That argument says that we should move it to `graph.Builder`.

**Comment by kortschak** [comment]
The issue that I am concerned with still here is the difference in semantics between the `NewNode`/`AddNode` pair and `NewEdge`/`SetEdge` pair. `NewNode` does not add the node to the graphs, explicitly. However, the implementation of `NewEdge` that exists in dot/decode_test.go does add newly created edges to the graph. This needs to be reconciled.

**Comment by mewmew** [comment]
I'm fine with that. Then perhaps `graph.EdgeSetter` would be renamed to `graph.EdgeAdder` in accordance with `graph.NodeAdder`.

To further improve consistency, perhaps `NewEdge` should behave like `NewNode` in that it does not add the edge to the graph, only creates it, for later addition with `SetEdge`? It would make the `EdgeAdder` interface more consistent with `NodeAdder`, but most likely make it more annoying to use.

What are your thoughts?

```go
// EdgeAdder is an interface for adding edges to a graph.
type EdgeAdder interface {
	// NewEdge adds a new edge from the source to the destination node to the
	// graph, or returns the existing edge if already present.
	NewEdge(from, to graph.Node) graph.Edge

	// SetEdge adds an edge from one node to another.
	// If the graph supports node addition the nodes
	// will be added if they do not exist, otherwise
	// SetEdge will panic.
	// The behavior of an EdgeAdder when the IDs
	// returned by e.From and e.To are equal is
	// implementation-dependent.
	SetEdge(e Edge)
}

// NodeAdder is an interface for adding arbitrary nodes to a graph.
type NodeAdder interface {
	// NewNode returns a new Node with a unique
	// arbitrary ID.
	NewNode() Node

	// Adds a node to the graph. AddNode panics if
	// the added node ID matches an existing node ID.
	AddNode(Node)
}
```

**Comment by mewmew** [comment]
> The issue that I am concerned with still here is the difference in semantics between the NewNode/AddNode pair and NewEdge/SetEdge pair. NewNode does not add the node to the graphs, explicitly. However, the implementation of NewEdge that exists in dot/decode_test.go does add newly created edges to the graph. This needs to be reconciled.

My previous comment was written before I had a chance to ready you latest reply. I agree, we should figure out how to make them more consistent. Lets make the change so that NewEdge returns an edge that is not yet added to the graph, and see how it affects the current code in the graph decoders. Perhaps they may need a local helper function to make it more pleasant to use, and then we should discuss if all users would write such a helper function, and if that's the case whether convenience or consistency is valued highest.

**Comment by kortschak** [comment]
That SGTM (I figured we were two ships in the night there).

Do you want to do that? Alteration of the decode_test.go and your most recent graph code mentioned about would be good test cases.
