### ISSUE TITLE
optimize: Make sure that linesearchers handle NaN after a step.

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/gonum#667]

**Comment by vladimir-ch** [comment]
I've looked into this now again and I think I would close it without any action. My idea was that if we start at a non-NaN location, then for a sufficiently small steps a reasonable function will be also non-NaN. So if we encounter a NaN during a linesearch, then theoretically we can always force the step towards zero, towards the non-NaN area. However, if we start assuming that the objective function can return a NaN at any point, the linesearcher logic becomes too complex. For `Bisection` it is still doable but for `MoreThuente` not, that linesearcher inherently assumes that the objective function is smooth and defined everywhere. What do you think, @btracey ?

**Comment by btracey** [comment]
I agree. These black-box methods need to simultaneously assume that the function can be NaN anywhere and that there is some sort of smoothness property. I believe when the issue was filed I thought maybe one of the linesearcher methods would not correctly backstep if it encountered a NaN. I think we should treat NaN as +Inf

**Comment by vladimir-ch** [comment]
Ok, I close this.
