### ISSUE TITLE
unit: Package documentation has unimplemented features

### ISSUE THREAD

**Issue by scott-maddox** [gonum/gonum#730]
Many of the examples in `doc.go` do not work. For example, `unit.Temperature`, `unit.Pressure`, `unit.Density`, `unit.Bar`, `unit.Energy`, and `unit.Area` do not exist.

Currently, it is unclear how this package is meant to be used. Are the features in the documentation features that used to exist that are now deprecated, or are they features that are still desired? I would be happy to help improve the package and documentation, if the authors could explain their vision.

Thanks!

**Comment by jonshao** [comment]
Seems like this is still an issue. Have there been any developments?

**Comment by kortschak** [comment]
A more [complete example](https://godoc.org/gonum.org/v1/gonum/unit#ex-package--Horsepower) was recently added. Can you point to specific issues in the docs and/or examples that you would like to see?

**Comment by kortschak** [comment]
OK. Just taken a look. The examples in the doc.go comment should be removed and replaced with similar runnable examples. The truth of some of that documentation is clearly rotted. However because of the design of the package user-provided concrete types can be used to illustrate the same behaviours. I think that we probably should not be providing derived types, but that could change. I may be able to find some time to do this over the next few days.

@btracey Do you have any views on this?

**Comment by kortschak** [comment]
To help with this, I'd like to propose a ".../unit/constant" package that includes `float64`-derived types satisfying `unit.Uniter`. This allows us to provide physical constants in a straightforward way.

**Comment by btracey** [comment]
I agree we should clean it up. I think we probably should follow the existing documentation rather than the existing code and split out the SI prefixes. This would have been clearly better from the start except for the fact that `Kilogram` being the base unit messes everything up. Maybe we provide prefixes for everything except Kilogram where we provide the full suite? 

I think we should provide derived types. I don't know how to draw the line on where given that there are an infinite number of them. I would say that most things with an SI name (Joules, Pascals, etc.) is good to add, plus a couple common ones without names (Acceleration, Area, Speed). 

I like the idea of a `constant` package in Unit.

**Comment by kortschak** [comment]
I have added the base SI units to the package in #890. I don't think that it's necessary to add derived types after putting together the contant package; user types that satisfy `unit.Uniter` are enough. I would like to merge #890 and then write some examples that show how compile-time type safe types can be written. This makes a base to work from. If a limited set of derived types is seen to be needed then those can be added later.

One thing that I found I would have like in unit is the capacity to extract the `Dimensions` from a `*unit.Unit`. This is currently not possible. I worked around it, but it was irritating.

**Comment by btracey** [comment]
SGTM

**Comment by btracey** [comment]
I would like to get rid of the `formatted` field in unit though. Instead, just run u.dimensions.String() every time. It’s currently a race condition to print a unit concurrently, which is totally surprising and an unnecessary restriction.

**Comment by kortschak** [comment]
That's in #90.
