### ISSUE TITLE
graph: Copy creates new edges

### ISSUE THREAD

**Issue by sevein** [gonum/gonum#824]
### What are you trying to do?

Create a copy of a graph with `graph.Copy`.

### What did you expect to happen?

My graph had custom nodes and edges values implementing `encoding.Attributer`.
I expected the copy to use the same values.

### What actually happened?

My nodes were used to build the new graph. However the edges were created from scratch:

    dst.SetEdge(dst.NewEdge(u, v))

Instead of something like the following:

    dst.SetEdge(src.Edge(u.ID(), to.Node.ID()))

I'm not sure if this is a bug, sorry for the noise in advance!

### What version of Go and Gonum are you using?

- go: `go version go1.11.4 linux/amd64`
- gonum: `v0.0.0-20190123113241-dd4cc715c58a` (`go.mod`)

### Does this issue reproduce with the current master?

Yes.

**Comment by kortschak** [comment]
Yes, this is working as intended. Perhaps we should clarify the documentation; really what the copy routines do is copy the topology. The intention (which I now see I actually did not completely capture, is to make sure that the copies are separate, using `dst`'s edges would prevent that because there would be references to nodes in `src` within `dst` (this still may currently happen because nodes copied from `src` to `dst` may be pointer or other types with reference-like characteristics.

Because of the massive flexibility with which graphs can be used, I'm not convinced that we can have a generic does-exactly-what-you-want-for-every-ocassion copy function.

I think the best I can do is break it further (making sure that nodes are not copied either) and document that only topology is copied.

Note that with clever use of interfaces, you can actually get a complete copy using these functions, but it's probably easier to just copy-paste the code there and add in the things that you want done for your types.

**Comment by kortschak** [comment]
There are potential further complications; when a copy is made from an undirected graph to a directed graph with the edges taken directly from the `src`, the documented behaviour of having both directions represented in the `dst` may be broken (it is with all the implementations in simple). The is because, at least in simple, edges for u--v and v--u are both returned as edge(u,v), so when that is written into `dst`, only the u->v edge is retained. This is a corner case of https://github.com/gonum/graph/issues/87.

**Comment by sevein** [comment]
Thanks @kortschak, that's really helpful!

> The user would then be responsible for breaking links between the values if necessary (easily done by wrapping the value in a struct that copies out nodes and edges if necessary).

Out of curiosity, that would require the use of unexported fields?

**Comment by kortschak** [comment]
No, I'd just write a `type copyShim struct { graph.Graph }` (substitute the appropriate type) that has `Node` and `Edge` methods that ensure that the returned nodes and edges do not retain references to the embedded graph that will be mutated. In many this may not be necessary (the graphs in simple don't need this and the test graphs in encoding/dot may not either even though the copies would share `encoding.Attribute` values — providing the values are not altered). As is often the case, your use decides what needs to happen.

Also note that `Copy` doesn't copy graph level encdoing attributes, so that's up to you.

**Comment by sevein** [comment]
That makes sense, thank you so much @kortschak!

**Comment by sevein** [comment]
@kortschak, thank you so much!

**Comment by kortschak** [comment]
Sorry it took so long; it required thought about the best way to tackle it. I think we have that.
