### ISSUE TITLE
unit: clean up unit package

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#90]
The unit package has a lot of problems. These should be cleaned up. Here are my suggestions

- [x] Clean up basic documentation so that it actually matches the code
- [x] Remove the (incorrect) comment examples and make them test Examples
- [x] Do not provide so many constants for the units. Not `unit.Millimeter`, instead just supply a `unit.Milli` constant, so it can be `unit.Milli * unit.Meter`. Slightly less pretty, but drastically reduces the API surface and makes it more composable with outside code
- [ ] ~~Redefine the `Unit` combination methods to match the `mat` types. For example, `Add` should take in two arguments and store to the receiver~~
- [x] Remove the `formatted` field from `Unit`. It introduces unnecessary state
- [x] Update the autogeneration to use `go generate`. 
- [x] It seems like the formatting code for unit types needs fixing.

**Comment by kortschak** [comment]
I'm not sure about the 4 point here. There is only a concrete `Unit` type, so it's reasonable to be able to chain things.

**Comment by btracey** [comment]
Will ponder.

**Comment by kortschak** [comment]
What is the plan for the `formatted` field?

**Comment by kortschak** [comment]
I've been thinking more about the `formatted` field and I think it should stay. It saves potentially large numbers of allocations (one per print). The race that can exist can be fixed by addition of a `sync.RWMutex` protecting it.

Related to the combination behaviour point. The zero value should be usable for these; if the `dimensions` field is nil (as opposed to empty), they should be set to the appropriate state.

**Comment by btracey** [comment]
I think all that's left of this is point 3

**Comment by kortschak** [comment]
Agreed
